Attribute VB_Name = "ModuloUtilidades"
Option Explicit

Global nroFactura As Long

Public Function ValidadorMsg() As Boolean
If Facturacion.txtNombre.Text = "" Then
    MsgBox "Ingrese el nombre del cliente", vbInformation, "Doom"
    ValidadorMsg = True
ElseIf Facturacion.txtCuit.Text = "" Then
    MsgBox "Ingrese el C.U.I.T. del cliente", vbInformation, "Doom"
    ValidadorMsg = True
ElseIf Facturacion.txtDireccion.Text = "" Then
    MsgBox "Ingrese la dirección del cliente", vbInformation, "Doom"
    ValidadorMsg = True
Else
    ValidadorMsg = False
End If
End Function


' Convierte un valor de texto en número limpio
Public Function LimpiarValor(ByVal texto As String) As Double
    Dim valorLimpio As String
    valorLimpio = Replace(texto, "$", "")
    valorLimpio = Replace(valorLimpio, ",", "")
    valorLimpio = Trim(valorLimpio)
    
    If IsNumeric(valorLimpio) Then
        LimpiarValor = Val(valorLimpio)
    Else
        LimpiarValor = 0
    End If
End Function

' Formatea un número como precio
Public Function FormatoPrecio(ByVal Valor As Double) As String
    FormatoPrecio = "$" & Format$(Valor, "#,##0.00")
End Function

' Muestra una alerta estándar
Public Sub MostrarAlerta(ByVal mensaje As String)
    MsgBox mensaje, vbExclamation, "Advertencia"
End Sub

Public Function FormatearNumeroFactura(ByVal numero As Long) As String
    FormatearNumeroFactura = Format(numero, "00000000")
End Function

Public Function GenerarComprobante(ByVal subTotal As Double, iva As Double, total As Double, formulario As Object) As String
    Dim Archivo As Integer
    Dim ruta As String
    Dim i As Integer
    Dim rutaImagen1 As String
    Dim rutaImagen2 As String
    Dim rutaImagen3 As String
    
'    Dim subTotal As Double, iva As Double, total As Double
'    ruta = "C:\comprobante.html"
    ruta = Environ$("USERPROFILE") & "\Documents\comprobante.html"

    If Right(App.Path, 1) = "\" Then
        rutaImagen1 = App.Path & "LOGO1.JPG"
        rutaImagen2 = App.Path & "LOGO2.JPG"
        rutaImagen3 = App.Path & "LOGO3.JPG"
    Else
        rutaImagen1 = App.Path & "\" & "LOGO1.JPG"
        MsgBox rutaImagen1
        MsgBox App.Path & "LOGO1.JPG"
        rutaImagen2 = App.Path & "\" & "LOGO2.JPG"
        rutaImagen3 = App.Path & "\" & "LOGO3.JPG"
    End If

    Archivo = FreeFile()
    Open ruta For Output As #Archivo
    
    Print #Archivo, "<html><head><title>Factura</title></head><body>"
    Print #Archivo, "<style>"
    Print #Archivo, "body { font-family: Arial, sans-serif; width: 800px; margin: auto; }"
    Print #Archivo, ".container { border: 1px solid #000; padding: 0; }"
    Print #Archivo, ".header { display: flex; border-bottom: 1px solid #000; position: relative; }"
    Print #Archivo, ".logo-section { width: 50%; padding: 10px; }"
    Print #Archivo, ".logo { width: 350px; display: block; }"
    Print #Archivo, ".company-info { font-size: 12px; margin: 0; }"
    Print #Archivo, ".company-space { margin-bottom: 15px; }"
    Print #Archivo, ".company-margin { margin: 0 50px;} "
    Print #Archivo, ".company-name { font-weight: bold; }"
    Print #Archivo, ".email { color: blue; }"
    Print #Archivo, ".letter-box {  width: 7%; display: flex; flex-direction: column; height: 100%; /* Añadir posición relativa */ }"
    Print #Archivo, ".vertical-blue-line { position: absolute; top: 49.5%; left: 50%; width: 1px; height: 102.5px; background-color: black; print-color-adjust: exact; -webkit-print-color-adjust: exact; }"
    Print #Archivo, ".letter { font-size: 36px; "
    Print #Archivo, "  text-align: center;"
    Print #Archivo, "  height: 100%; /* Ocupa todo el alto disponible */"
    Print #Archivo, "  display: flex;"
    Print #Archivo, "  flex-direction: column;"
    Print #Archivo, "  justify-content: center;}"
    Print #Archivo, ".letter-border { "
    Print #Archivo, "  border-left: 1px solid #000;"
    Print #Archivo, "  border-right: 1px solid #000;"
    Print #Archivo, "  border-bottom: 1px solid #000;"
    Print #Archivo, "  height: 100%; /* Ocupa todo el alto disponible */"
    Print #Archivo, "  display: flex;"
    Print #Archivo, "  align-items: center; /* Centra el contenido verticalmente */"
    Print #Archivo, "  justify-content: center; /* Centra el contenido horizontalmente */"
    Print #Archivo, "  min-height: 80px; /* Establece una altura mínima */"
    Print #Archivo, "  padding: 10px 0; /* Añade espacio arriba y abajo */} "
    Print #Archivo, ".factura-section { width: 50%; padding: 10px; display: flex; flex-direction: column; }"
    Print #Archivo, ".factura-label { font-size: 14px; text-align: left; margin-bottom: 10px; }"
    Print #Archivo, ".factura-num { font-size: 23px; margin-bottom: 20px; }"
    Print #Archivo, ".factura-num-dos {margin-right: 6px;}"
    Print #Archivo, ".factura-num-font {font-size: 28px; font-family: 'Courier New', monospace; color: gray}"
    Print #Archivo, ".factura-info { text-align: left; margin-top: 35px;}"
    Print #Archivo, ".vertical-line { position: absolute; top: 70px; left: 76%; width: 1px; height: calc(100% - 70px); background-color: #000; }"
    Print #Archivo, ".items-table { width: 100%; border-collapse: collapse; }"
    Print #Archivo, ".items-table th, .items-table td {"
    Print #Archivo, "  width: 25%;"
    Print #Archivo, "  text-align: center;"
    Print #Archivo, "  font-size: 12px;"
    Print #Archivo, "}"
    Print #Archivo, ".watermark { position: relative; height: 400px; }"
    Print #Archivo, ".watermark-content { position: absolute; width: 100%; height: 100%; display: flex; justify-content: center; align-items: center; opacity: 0.1; }"
    Print #Archivo, ".watermark-logos { display: flex; justify-content: center; }"
    Print #Archivo, ".watermark-logo { margin: 0 20px; }"
    Print #Archivo, ".totals-section { "
    Print #Archivo, "  display: flex;"
    Print #Archivo, "  margin-bottom: 10px;"
    Print #Archivo, "}"
    Print #Archivo, ".totals-section-border {"
    Print #Archivo, "  position: relative;"
    Print #Archivo, "  height: 10px; /* Altura del espacio que contiene el borde */"
    Print #Archivo, "  margin: 0 auto;"
    Print #Archivo, "  width: 94%;"
    Print #Archivo, "  border-top: 1px dashed #000;"
    Print #Archivo, "}"
    Print #Archivo, ".totals-section-border::before {"
    Print #Archivo, "  content: '';"
    Print #Archivo, "  position: absolute;"
    Print #Archivo, "  top: 0;"
    Print #Archivo, "  left: 10%; /* Ajusta este valor para controlar dónde comienza el borde */"
    Print #Archivo, "  width: 95%; /* Ajusta este valor para controlar el ancho del borde */"
    Print #Archivo, "  height: 1px;"
    Print #Archivo, "  background-color: transparent; /* Elimina el fondo sólido */"
    Print #Archivo, "}"
    Print #Archivo, ".subtotal-section { "
    Print #Archivo, "  width: 40%; "
    Print #Archivo, "  padding: 10px; "
    Print #Archivo, "  font-size: 12px; "
    Print #Archivo, "}"
    Print #Archivo, ".total-section { "
    Print #Archivo, "  width: 60%; "
    Print #Archivo, "  padding: 10px; "
    Print #Archivo, "  text-align: right; "
    Print #Archivo, "  font-size: 14px; "
    Print #Archivo, "}"
    Print #Archivo, ".footer {padding: 0 10px; font-size: 10px; text-align: left; margin: 15px 0;}"
    Print #Archivo, ".footer p { margin: 0; }"
    Print #Archivo, "@media print {"
    Print #Archivo, "  .no-print, .no-print * {"
    Print #Archivo, "    display: none !important;"
    Print #Archivo, "    visibility: hidden !important;"
    Print #Archivo, "  }"
    Print #Archivo, "  .vertical-blue-line {"
    Print #Archivo, "    position: absolute;"
    Print #Archivo, "    top: 49.5%;"
    Print #Archivo, "    left: 50%;"
    Print #Archivo, "    width: 1px;"
    Print #Archivo, "    height: 103px;"
    Print #Archivo, "    background-color: black;"
    Print #Archivo, "    print-color-adjust: exact;"
    Print #Archivo, "    -webkit-print-color-adjust: exact;"
    Print #Archivo, "}"
    Print #Archivo, "  @page {"
    Print #Archivo, "    margin: 0.5cm;"
    Print #Archivo, "    size: auto;"
    Print #Archivo, "  }"
    Print #Archivo, "  html {"
    Print #Archivo, "    -webkit-print-color-adjust: exact !important;"
    Print #Archivo, "    print-color-adjust: exact !important;"
    Print #Archivo, "  }"
    Print #Archivo, "  body > *:not(.container) {"
    Print #Archivo, "    display: none !important;"
    Print #Archivo, "  }"
    Print #Archivo, "  .header-date, .print-timestamp, .browser-info {"
    Print #Archivo, "    display: none !important;"
    Print #Archivo, "  }"
    Print #Archivo, "}"
    Print #Archivo, "</style>"
    Print #Archivo, "<div class='container'>"
    Print #Archivo, "<div class='header'>"
    Print #Archivo, "  <div class='logo-section'>"
    Print #Archivo, "    <img src=" & rutaImagen1 & " class='logo'>"
    Print #Archivo, "    <div class='company-margin'>"
    Print #Archivo, "      <p class='company-info company-name'>NEUMATICOS ARTURO S.R.L.</p>"
    Print #Archivo, "      <p class='company-info'>AV. SAN MARTIN 1695 - 1678 CASEROS</p>"
    Print #Archivo, "      <p class='company-info'>TEL.: (011) 4734 - 8476</p>"
    Print #Archivo, "      <p class='company-info email'>ventas@neumaticosarturo.com.ar</p>"
    Print #Archivo, "      <p class='company-info'>I.V.A.: Responsable Inscripto</p>"
    Print #Archivo, "    </div>"
    Print #Archivo, "  </div>"
    Print #Archivo, "  <div class='letter-box'>"
    Print #Archivo, "    <div class='flex letter'>"
    Print #Archivo, "      <div class='letter-border'>"
    Print #Archivo, "          A"
    Print #Archivo, "      </div>"
    Print #Archivo, "      <div class='vertical-blue-line'></div>"
    Print #Archivo, "    </div>"
    Print #Archivo, "  </div>"
    Print #Archivo, "  <div class='factura-section'>"
    Print #Archivo, "    <div class='factura-label'>FACTURA</div>"
    Print #Archivo, "    <div class='factura-num'><span class='factura-num-dos'>N°0001- " & "</span> <span class='factura-num-Font'>" & Format(nroFactura, "00000000") & "</span></div>"
    Print #Archivo, "    <div class='factura-info'>"
    Print #Archivo, "      <p class='company-info company-space'>FECHA: " & Facturacion.fecEmision & "</p>"
    Print #Archivo, "      <p class='company-info'>C.U.I.T.: 33-71457404-9</p>"
    Print #Archivo, "      <p class='company-info'>ING. BRUTOS: 33-71457404-9</p>"
    Print #Archivo, "      <p class='company-info'>INICIO DE ACTIVIDADES: 08/2014</p>"
    Print #Archivo, "    </div>"
    Print #Archivo, "  </div>"
    Print #Archivo, "</div>"
    Print #Archivo, "<div style='border-bottom: 1px solid #000; height: 60px'>"
    Print #Archivo, "<div style='border-bottom: 1px solid #000; height: 60px;'>"
    Print #Archivo, "<div style='display: flex; justify-content: space-between; padding:0 10px; font-size: small;'>"
    Print #Archivo, "<p style='margin: 0.5rem 0 0 0'>" & Facturacion.txtNombre.Text & "</p>"
    Print #Archivo, "<p style='margin: 0.5rem 0 0 0'>C.U.I.T.: " & Facturacion.txtCuit.Text & "</p>"
    Print #Archivo, "</div>"
    Print #Archivo, "<div style='display: flex; justify-content: space-between; padding:0 10px; font-size: small;'>"
    Print #Archivo, "<p style='margin: 1rem 0 0 0'>" & Facturacion.txtDireccion.Text & "</p>"
    Print #Archivo, "<p style='margin: 1rem 0 0 0'>IVA RESPONSABLE INSCRIPTO</p>"
    Print #Archivo, "</div>"
    Print #Archivo, "</div>"
    Print #Archivo, "</div>"
    Print #Archivo, "<table class='items-table'>"
    Print #Archivo, "  <tr>"
    Print #Archivo, "    <th style='padding: 5px; border-bottom: none; width: 25%; text-align: center; color: gray'>CANTIDAD</th>"
    Print #Archivo, "    <th style='padding: 5px; border-bottom: none; width: 32%; text-align: center; color: gray'>DESCRIPCION</th>"
    Print #Archivo, "    <th style='padding: 5px; border-bottom: none; width: 25%; text-align: center; color: gray'>P.UNITARIO</th>"
    Print #Archivo, "    <th style='padding: 5px; border-bottom: none; width: 25%; text-align: center; color: gray'>TOTAL</th>"
    Print #Archivo, "  </tr>"
    Print #Archivo, "<tr><td colspan='4'>"
    Print #Archivo, "<div class='watermark'>"
    Print #Archivo, "  <div class='watermark-content'>"
    Print #Archivo, "    <div class='watermark-logos'>"
    Print #Archivo, "      <img src=" & rutaImagen3 & " class='watermark-logo' style='width: 300px'>"
    Print #Archivo, "      <img src=" & rutaImagen2 & " class='watermark-logo' style='width: 300px'>"
    Print #Archivo, "    </div>"
    Print #Archivo, "  </div>"
    Print #Archivo, "  <table style='width: 100%; border: none'>"

    ' Recorrer ListView y agregar filas a la tabla
    With formulario
    For i = 1 To .Grilla.ListItems.Count
        Dim Cantidad As Integer
        Dim Descripcion As String
        Dim PrecioUnitario As Double
        Dim totalProducto As Double

        Cantidad = .Grilla.ListItems(i).SubItems(2)
        Descripcion = .Grilla.ListItems(i).SubItems(1)
        PrecioUnitario = .Grilla.ListItems(i).SubItems(3)
        totalProducto = .Grilla.ListItems(i).SubItems(4)

        Print #Archivo, "<tr><td style='width: 25%; text-align: center'>" & Cantidad & "</td>"
        Print #Archivo, "<td style='width: 32%; text-align: left; text-transform: uppercase'>" & Descripcion & "</td>"
        Print #Archivo, "<td style='width: 25%; text-align: center'>" & Format(PrecioUnitario, "#,##0.00") & "</td>"
        Print #Archivo, "<td style='width: 25%; text-align: center'>" & Format(totalProducto, "#,##0.00") & "</td></tr>"

'        subTotal = subTotal + totalProducto
    Next i
    End With
    Print #Archivo, "  </table>"
    Print #Archivo, "</div>"
    Print #Archivo, "</td></tr>"
    Print #Archivo, "</table>"
    Print #Archivo, "<div style='display: flex'>"
    Print #Archivo, "  <div class='subtotal-section'>"
    Print #Archivo, "    <div style='display: flex'> "
    Print #Archivo, "    <div style='margin-right: 80px'>SUBTOTAL</div>"
    Print #Archivo, "    <div>IVA</div>"
    Print #Archivo, "  </div>"
    Print #Archivo, "<div style='display: flex; margin-top: 5px;'>"
    Print #Archivo, "<div style='margin-right: 80px;'>" & Format$(subTotal, "#,##0.00") & "</div>"
    Print #Archivo, "<div>(21.00)</div>"
    Print #Archivo, "</div>"
    Print #Archivo, "  </div>"
    Print #Archivo, "  <div class='total-section'>"
    Print #Archivo, "    <div>CONCEPTOS NO GRAVADOS</div>"
    Print #Archivo, "    <br><br>"
    Print #Archivo, "    <div style='display: flex; justify-content: space-between; font-size: 16px; font-weight: bold; text-align: left; padding-left: 50%;'>TOTAL $ <span>" & Format$(total, "#,##0.00") & "</span></div>"
    Print #Archivo, "  </div>"
    Print #Archivo, "</div>"
    Print #Archivo, "<div class='totals-section-border'></div>"
    Print #Archivo, "<div class='footer'>"
    Print #Archivo, "  <p>C.A.I. N 2175-19625194739</p>"
    Print #Archivo, "  <p>Fecha de Vencimiento: 11/09/2027</p>"
    Print #Archivo, "  <p style='margin-left: 20px;'>REGISTRO PHG3523973</p>"
    Print #Archivo, "</div>"
    Print #Archivo, "</div>"
    Print #Archivo, "</body></html>"

    Close #Archivo
    
    ' Abrir el comprobante en el navegador
    Shell "cmd /c start " & ruta, vbNormalFocus
End Function

Public Function GenerarComprobante2(ByVal subTotal As Double, iva As Double, total As Double, formulario As Object) As String
    Dim Archivo As Integer
    Dim ruta As String
    Dim i As Integer
    Dim rutaImagen1 As String
    Dim rutaImagen2 As String
    Dim rutaImagen3 As String
    Dim rutaImagen4 As String
    Dim rutaImagen5 As String

    If Right(App.Path, 1) = "\" Then
        rutaImagen1 = App.Path & "LOGO4.JPG"
        rutaImagen2 = App.Path & "LOGO5.JPG"
        rutaImagen3 = App.Path & "LOGO6.JPG"
        rutaImagen4 = App.Path & "LOGO7.JPG"
        rutaImagen5 = App.Path & "LOGO8.JPG"
    Else
        rutaImagen1 = App.Path & "\" & "LOGO4.JPG"
        rutaImagen2 = App.Path & "\" & "LOGO5.JPG"
        rutaImagen3 = App.Path & "\" & "LOGO6.JPG"
        rutaImagen4 = App.Path & "\" & "LOGO7.JPG"
        rutaImagen5 = App.Path & "\" & "LOGO8.JPG"
    End If
    
'    ruta = "C:\comprobante2.html"
    ruta = Environ$("USERPROFILE") & "\Documents\comprobante2.html"
    
    Archivo = FreeFile()
    Open ruta For Output As #Archivo
    
    Print #Archivo, "<html>"
    Print #Archivo, "<head>"
    Print #Archivo, "    <title>Factura Federal Parts</title>"
    Print #Archivo, "    <style>"
    Print #Archivo, "        body {"
    Print #Archivo, "            font-family: Arial, sans-serif;"
    Print #Archivo, "            width: 800px;"
    Print #Archivo, "            margin: auto;"
    Print #Archivo, "            background-color: #a9dff9;"
    Print #Archivo, "        }"
    Print #Archivo, "        .container {"
    Print #Archivo, "            padding: 0;"
    Print #Archivo, "            background-color: #a9dff9;"
    Print #Archivo, "        }"
    Print #Archivo, "        .header {"
    Print #Archivo, "            display: flex;"
    Print #Archivo, "            justify-content: space-between;"
    Print #Archivo, "            padding: 10px 0px;"
    Print #Archivo, "            margin-left: 35px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .logo-section { display: flex; width: 45%; }"
    Print #Archivo, "        .logo-fp {"
    Print #Archivo, "            display: flex;"
    Print #Archivo, "            flex-direction: column;"
    Print #Archivo, "            margin-left: 10px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .fp-text {"
    Print #Archivo, "            color: #FF0000;"
    Print #Archivo, "            letter-spacing: 7px;"
    Print #Archivo, "            font-family: Arial, Helvetica, sans-serif;"
    Print #Archivo, "            font-size: 23px;"
    Print #Archivo, "            font-weight: 800;"
    Print #Archivo, "            margin: 0;"
    Print #Archivo, "        }"
    Print #Archivo, "        .repuestos-text {"
    Print #Archivo, "            letter-spacing: 2px;"
    Print #Archivo, "            font-size: 17px;"
    Print #Archivo, "            font-weight: bold;"
    Print #Archivo, "            margin: 0;"
    Print #Archivo, "        }"
    Print #Archivo, "        .phone-numbers {"
    Print #Archivo, "            font-size: 14px;"
    Print #Archivo, "            margin-top: 10px;"
    Print #Archivo, "            font-weight: bold;"
    Print #Archivo, "        }"
    Print #Archivo, "        .blue-square {"
    Print #Archivo, "            width: 80px;"
    Print #Archivo, "            height: 80px;"
    Print #Archivo, "            background-color: #000080;"
    Print #Archivo, "            margin-right: 10px;"
    Print #Archivo, "            display: flex;"
    Print #Archivo, "            justify-content: center;"
    Print #Archivo, "            align-items: center;"
    Print #Archivo, "        }"
    Print #Archivo, "        .fp-logo {"
    Print #Archivo, "            color: #FF0000;"
    Print #Archivo, "            font-size: 36px;"
    Print #Archivo, "            font-weight: bold;"
    Print #Archivo, "        }"
    Print #Archivo, "        .company-box {"
    Print #Archivo, "            border: 1px solid #000;"
    Print #Archivo, "            padding: 13px;"
    Print #Archivo, "            margin-top: 22px;"
    Print #Archivo, "            background-color: white;"
    Print #Archivo, "            width: 92%;"
    Print #Archivo, "            font-size: 12px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .invoice-box {"
    Print #Archivo, "            display: flex;"
    Print #Archivo, "            gap:1rem;"
    Print #Archivo, "            align-items: center;"
    Print #Archivo, "            border: 1px solid #000;"
    Print #Archivo, "            padding: 8.5px;"
    Print #Archivo, "            background-color: white;"
    Print #Archivo, "            margin-top: 10px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .tfact-box {"
    Print #Archivo, "            border: 1px solid #000;"
    Print #Archivo, "            padding: 9px 10px;"
    Print #Archivo, "            background-color: white;"
    Print #Archivo, "            width: 85%;"
    Print #Archivo, "        }"
    Print #Archivo, "        .tfact-box p {"
    Print #Archivo, "            text-align: center;"
    Print #Archivo, "            font-size: 30px;"
    Print #Archivo, "            margin-block-start: 10px;"
    Print #Archivo, "            margin-block-end: 10px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .original-copy {"
    Print #Archivo, "            text-align: center;"
    Print #Archivo, "            font-size: 12px;"
    Print #Archivo, "            margin-bottom: 10px;"
    Print #Archivo, "            padding: 25px 0;"
    Print #Archivo, "        }"
    Print #Archivo, "        .factura-text {"
    Print #Archivo, "            font-size: 18px;"
    Print #Archivo, "            margin-bottom: 5px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .factura-num {"
    Print #Archivo, "            font-family: 'Courier New', monospace;"
    Print #Archivo, "            font-size: 16px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .date-section {"
    Print #Archivo, "            margin-top: 10px;"
    Print #Archivo, "            font-size: 12px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .side-logos {"
    Print #Archivo, "            display: flex;"
    Print #Archivo, "            flex-direction: column;"
    Print #Archivo, "            margin-right: 4rem;"
    Print #Archivo, "        }"
    Print #Archivo, "        .side-logo {"
    Print #Archivo, "            width: 100px;"
    Print #Archivo, "            height: 70px;"
    Print #Archivo, "            margin-bottom: 20px;"
    Print #Archivo, "            text-align: center;"
    Print #Archivo, "            display: flex;"
    Print #Archivo, "            justify-content: center;"
    Print #Archivo, "            align-items: center;"
    Print #Archivo, "        }"
    Print #Archivo, "        .bosch-logo {"
    Print #Archivo, "            background-color: #FF0000;"
    Print #Archivo, "            color: white;"
    Print #Archivo, "            font-size: 24px;"
    Print #Archivo, "            font-weight: bold;"
    Print #Archivo, "        }"
    Print #Archivo, "        .stanadyne-logo {"
    Print #Archivo, "            background-color: #000080;"
    Print #Archivo, "            color: white;"
    Print #Archivo, "            font-size: 16px;"
    Print #Archivo, "            font-weight: bold;"
    Print #Archivo, "        }"
    Print #Archivo, "        .delphi-logo {"
    Print #Archivo, "            background-color: #FF0000;"
    Print #Archivo, "            color: white;"
    Print #Archivo, "            font-size: 20px;"
    Print #Archivo, "            font-weight: bold;"
    Print #Archivo, "            border-radius: 50%;"
    Print #Archivo, "            width: 100px;"
    Print #Archivo, "            height: 100px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .denso-logo {"
    Print #Archivo, "            background-color: #FF0000;"
    Print #Archivo, "            color: white;"
    Print #Archivo, "            font-size: 20px;"
    Print #Archivo, "            font-weight: bold;"
    Print #Archivo, "        }"
    Print #Archivo, "        .client-section {"
    Print #Archivo, "            border: 1px solid #000;"
    Print #Archivo, "            background-color: white;"
    Print #Archivo, "            min-height: 65px;"
    Print #Archivo, "            margin-bottom: 10px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .items-table {"
    Print #Archivo, "            width: 100%;"
    Print #Archivo, "            background-color: white;"
    Print #Archivo, "            border-top: 1px solid black;"
    Print #Archivo, "            border-left: 1px solid black;"
    Print #Archivo, "            border-right: 1px solid black;"
    Print #Archivo, "        }"
    Print #Archivo, "        .items-table th {"
    Print #Archivo, "            padding: 5px;"
    Print #Archivo, "            text-align: center;"
    Print #Archivo, "            background-color: white;"
    Print #Archivo, "        }"
    Print #Archivo, "        .items-table td {"
    Print #Archivo, "            text-align: center;"
    Print #Archivo, "        }"
    Print #Archivo, "        .totals-section {"
    Print #Archivo, "            display: flex;"
    Print #Archivo, "            justify-content: space-between;"
    Print #Archivo, "            margin: 10px 20px;"
    Print #Archivo, "            font-size: 12px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .subtotal-section {"
    Print #Archivo, "            display: flex;"
    Print #Archivo, "            gap: 30px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .total-amount {"
    Print #Archivo, "            font-weight: bold;"
    Print #Archivo, "            font-size: 16px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .footer-section {"
    Print #Archivo, "            padding: 0 10px 10px 10px;"
    Print #Archivo, "            font-size: 12px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .footer-line {"
    Print #Archivo, "            display: flex;"
    Print #Archivo, "            justify-content: space-between;"
    Print #Archivo, "            margin-bottom: 10px;"
    Print #Archivo, "        }"
    Print #Archivo, "        .consumer-protection {"
    Print #Archivo, "            font-size: 14px;"
    Print #Archivo, "            padding: 10px 0 10px 10px;"
    Print #Archivo, "            font-weight: bold;"
    Print #Archivo, "            width: 83.5%;"
    Print #Archivo, "            margin-left: 8.4rem;"
    Print #Archivo, "            background-color: white;"
    Print #Archivo, "        }"
    Print #Archivo, "        .watermark { position: relative; height: 400px; }"
    Print #Archivo, "        .subtotal-section { "
    Print #Archivo, "            display: block;"
    Print #Archivo, "            width: 40%; "
    Print #Archivo, "            padding: 10px; "
    Print #Archivo, "            font-size: 12px; "
    Print #Archivo, "        }"
    Print #Archivo, "        .total-section { "
    Print #Archivo, "            width: 60%; "
    Print #Archivo, "            padding: 10px; "
    Print #Archivo, "            text-align: right; "
    Print #Archivo, "            font-size: 14px; "
    Print #Archivo, "        }"
    Print #Archivo, "        @media print {"
    Print #Archivo, "            .no-print, .no-print * {"
    Print #Archivo, "                display: none !important;"
    Print #Archivo, "                visibility: hidden !important;"
    Print #Archivo, "            }"
    Print #Archivo, "            .vertical-blue-line {"
    Print #Archivo, "                position: absolute;"
    Print #Archivo, "                top: 49.5%;"
    Print #Archivo, "                left: 50%;"
    Print #Archivo, "                width: 1px;"
    Print #Archivo, "                height: 103px;"
    Print #Archivo, "                background-color: black;"
    Print #Archivo, "                print-color-adjust: exact;"
    Print #Archivo, "                -webkit-print-color-adjust: exact;"
    Print #Archivo, "            }"
    Print #Archivo, "            @page {"
    Print #Archivo, "                margin: 0.5cm;"
    Print #Archivo, "                size: auto;"
    Print #Archivo, "                background-color: #a9dff9 !important;"
    Print #Archivo, "            }"
    Print #Archivo, "            html {"
    Print #Archivo, "                -webkit-print-color-adjust: exact !important;"
    Print #Archivo, "                print-color-adjust: exact !important;"
    Print #Archivo, "            }"
    Print #Archivo, "            body > *:not(.container) {"
    Print #Archivo, "                display: none !important;"
    Print #Archivo, "            }"
    Print #Archivo, "            .header-date, .print-timestamp, .browser-info {"
    Print #Archivo, "                display: none !important;"
    Print #Archivo, "            }"
    Print #Archivo, "        }"
    
    'NUEVO 30/04/2025
    Print #Archivo, " table { "
    Print #Archivo, " width: 100%;"
    Print #Archivo, " border-collapse: collapse;"
    Print #Archivo, " font-size: 12px;"
    Print #Archivo, " }"
    Print #Archivo, " thead th {"
    Print #Archivo, " padding: 4px 6px;"
    Print #Archivo, " text-align: left;"
    Print #Archivo, " }"
    Print #Archivo, " tbody {"
    Print #Archivo, " height: 300px; /* Altura fija o mínima */"
    Print #Archivo, " display: block;"
    Print #Archivo, " }"
    Print #Archivo, " tbody tr {"
    Print #Archivo, " display: table;"
    Print #Archivo, " width: 100%;"
    Print #Archivo, " table-layout: fixed;"
    Print #Archivo, " }"
    Print #Archivo, " tbody td {"
    Print #Archivo, " padding: 3px 5px;"
    Print #Archivo, " vertical-align: top;"
    Print #Archivo, " }"
    Print #Archivo, " th.col-cantidad,"
    Print #Archivo, " td.col-cantidad {"
    Print #Archivo, " width: 5%;"
    Print #Archivo, " text-align: center;"
    Print #Archivo, " }"
    Print #Archivo, " th.col-descripcion,"
    Print #Archivo, " td.col-descripcion {"
    Print #Archivo, " width: 5%;"
    Print #Archivo, " }"
    Print #Archivo, " th.col-unitario,"
    Print #Archivo, " td.col-unitario,"
    Print #Archivo, " th.col-neto,"
    Print #Archivo, " td.col-neto {"
    Print #Archivo, " width: 20%;"
    Print #Archivo, " text-align: right;"
    Print #Archivo, " }"
    
    
    
    Print #Archivo, "    </style>"
    Print #Archivo, "</head>"
    Print #Archivo, "<body>"
    Print #Archivo, "    <div class='Container'>"
    Print #Archivo, "        <div class='header'>"
    Print #Archivo, "            <div class='logo-section'>"
    Print #Archivo, "                <img src=" & rutaImagen1 & " style='width: 70px; height: 100px; display: block'>"
    Print #Archivo, "                <div class='logo-fp'>"
    Print #Archivo, "                    <div>"
    Print #Archivo, "                        <p class='fp-Text'>Federal Parts</p>"
    Print #Archivo, "                        <p class='repuestos-Text'>REPUESTOS AUTOMOTOR</p>"
    Print #Archivo, "                    </div>"
    Print #Archivo, "                    <div class='phone-numbers'>"
    Print #Archivo, "                        <p style='margin: 0'>011-5713-7182</p>"
    Print #Archivo, "                        <p style='margin: 0'>011-4541-1361</p>"
    Print #Archivo, "                        <p style='margin: 0'>011-4541-2845</p>"
    Print #Archivo, "                    </div>"
    Print #Archivo, "                    <div class='company-box'>"
    Print #Archivo, "                        <p style='margin: 2px 0;'>FEDERAL PARTS S.R.L.</p>"
    Print #Archivo, "                        <p style='margin: 2px 0;'>JARAMILLO 3060 (1430)</p>"
    Print #Archivo, "                        <p style='margin: 2px 0;'>CIUDAD AUTONOMA DE BS. AS.</p>"
    Print #Archivo, "                        <p style='margin: 2px 0;'>IVA RESPONSABLE INSCRIPTO</p>"
    Print #Archivo, "                    </div>"
    Print #Archivo, "                </div>"
    Print #Archivo, "            </div>"
    Print #Archivo, "            <div>"
    Print #Archivo, "                <div class='tfact-box'>"
    Print #Archivo, "                    <p>A</p>"
    Print #Archivo, "                </div>"
    Print #Archivo, "            </div>"
    Print #Archivo, "            <div style='width: 20rem;'>"
    Print #Archivo, "                <div class='original-Copy'>ORIGINAL BLANCO / COPIA COLOR</div>"
    Print #Archivo, "                <div class='invoice-box'>"
    Print #Archivo, "                    <div class='factura-Text'>Factura</div>"
    Print #Archivo, "                    <div class='factura-num'>N°0001- <span>" & Format(nroFactura, "00000000") & "</span></div>"
    Print #Archivo, "                </div>"
    Print #Archivo, "                <div class='invoice-box'>"
    Print #Archivo, "                    <div class='Date-Section'>"
    Print #Archivo, "                        <p style='margin: 2px 0;'>Fecha: " & Facturacion.fecEmision & "</p>"
    Print #Archivo, "                        <p style='margin: 2px 0;'>C.U.I.T.: 30715978735</p>"
    Print #Archivo, "                        <p style='margin: 2px 0;'>Ingresos Brutos: 1547261-2</p>"
    Print #Archivo, "                        <p style='margin: 2px 0;'>Inicio de Actividades: 01/03/2018</p>"
    Print #Archivo, "                    </div>"
    Print #Archivo, "                </div>"
    Print #Archivo, "            </div>"
    Print #Archivo, "        </div>"
    Print #Archivo, "        <div style='display: flex;'>"
    Print #Archivo, "            <div class='side-logos'>"
    Print #Archivo, "                <img src=" & rutaImagen2 & " style=' width: 53px; height: 120px; display: block;'>"
    Print #Archivo, "                <img src=" & rutaImagen3 & " style=' width: 53px; height: 120px; display: block; margin-top: 10px;'>"
    Print #Archivo, "                <img src=" & rutaImagen4 & " style=' width: 53px; height: 120px; display: block; margin-top: 10px;'>"
    Print #Archivo, "                <img src=" & rutaImagen5 & " style=' width: 53px; height: 120px; display: block; margin-top: 10px;'>"
    Print #Archivo, "            </div>"
    Print #Archivo, "            <div style='width: 85%;'>"
    Print #Archivo, "                <div class='client-Section'>"
    Print #Archivo, "<div style='display: flex; justify-content: space-between; padding:0 10px;'>"
    Print #Archivo, "<p style='margin: 1rem 0 0 0'>" & Facturacion.txtNombre.Text & "</p>"
    Print #Archivo, "<p style='margin: 1rem 0 0 0'>C.U.I.T.: " & Facturacion.txtCuit.Text & "</p>"
    Print #Archivo, "</div>"
    Print #Archivo, "<div style='display: flex; justify-content: space-between; padding:0 10px;'>"
    Print #Archivo, "<p>" & Facturacion.txtDireccion.Text & "</p>"
    Print #Archivo, "<p>IVA RESPONSABLE INSCRIPTO</p>"
    Print #Archivo, "</div>"
    Print #Archivo, "                </div>"
    Print #Archivo, "                <div class='watermark'>"
    Print #Archivo, "                        <table class='items-Table' style='height: 80%;'>"
    Print #Archivo, "                            <tr>"
    Print #Archivo, "                                <th style='text-align: left; padding-left: 2rem;'>CANTIDAD</th>"
    Print #Archivo, "                                <th style='text-align: left;'>DESCRIPCION</th>"
    Print #Archivo, "                                <th>PRECIO UNITARIO</th>"
    Print #Archivo, "                                <th>PRECIO NETO</th>"
    Print #Archivo, "                            </tr>"
' Recorrer ListView y agregar filas a la tabla
    With formulario
    For i = 1 To .Grilla.ListItems.Count
        Dim Cantidad As Integer
        Dim Descripcion As String
        Dim PrecioUnitario As Double
        Dim totalProducto As Double

        Cantidad = .Grilla.ListItems(i).SubItems(2)
        Descripcion = .Grilla.ListItems(i).SubItems(1)
        PrecioUnitario = .Grilla.ListItems(i).SubItems(3)
        totalProducto = .Grilla.ListItems(i).SubItems(4)

        Print #Archivo, "<tr><td style='width: 15%; text-align: center'>" & Cantidad & "</td>"
        Print #Archivo, "<td style='width: 40%; text-align: left; text-transform: uppercase'>" & Descripcion & "</td>"
        Print #Archivo, "<td style='width: 25%; text-align: center'>" & Format(PrecioUnitario, "#,##0.00") & "</td>"
        Print #Archivo, "<td style='width: 25%; text-align: center'>" & Format(totalProducto, "#,##0.00") & "</td></tr>"

'        subTotal = subTotal + totalProducto
    Next i
    End With
    Print #Archivo, "                        </table>"
    Print #Archivo, "                        <div style='padding-top: 10px; text-align: center; background-color: white; border-left: 1px solid black; border-right: 1px solid black;'>"
    Print #Archivo, "                            <p class='fp-Text'>Federal Parts</p>"
    Print #Archivo, "                            <p class='repuestos-Text'>REPUESTOS AUTOMOTOR</p>"
    Print #Archivo, "                        </div>"
    Print #Archivo, "                        <div style='display: flex; padding-top: 15px; background-color: white; border-left: 1px solid black; border-right: 1px solid black;'>"
    Print #Archivo, "                            <div class='subtotal-section'>"
    Print #Archivo, "                                <div style='display: flex; align-items: center; gap: 2.5rem;'>"
    Print #Archivo, "                                    <div>SUBTOTAL</div>"
    Print #Archivo, "                                    <div style='width: 100px; flex-shrink: 0;'>ALICUOTA IVA</div>"
    Print #Archivo, "                                    <div style='width: 90px; flex-shrink: 0;'>IVA RECEP. IVA</div>"
    Print #Archivo, "                                    <div style='width: 90px; flex-shrink: 0;'>RECEP. OTROS</div>"
    Print #Archivo, "                                    <div style='width: 180px; flex-shrink: 0;'>CONCEPTOS NO GRAVADOS</div>"
    Print #Archivo, "                                </div>"
    Print #Archivo, "                                <div style='display: flex; margin-top: 5px;'>"
    Print #Archivo, "                                    <div style='margin-right: 54px;'>" & Format$(subTotal, "#,##0.00") & "</div>"
    Print #Archivo, "                                    <div style='margin-right: 98px;'>(21.00)</div>"
    Print #Archivo, "                                    <div style='margin-right: 320px;'>" & Format$(iva, "#,##0.00") & "</div>"
    Print #Archivo, "                                    <div>00.00</div>"
    Print #Archivo, "                                </div>"
    Print #Archivo, "                            </div>"
    Print #Archivo, "                        </div>"
    Print #Archivo, "                        <div style='padding: 10px; text-align: -webkit-right; background-color: white; border-left: 1px solid black; border-right: 1px solid black;'>"
    Print #Archivo, "                            <div style='width: 50%; text-align: right;'>"
    Print #Archivo, "                                <div style='margin-top: 10px; font-weight: bold; font-size: 18px; text-align: right;'>"
    Print #Archivo, "                                    <span style='margin-right: 10rem;'>TOTAL $</span>" & Format$(total, "#,##0.00")
    Print #Archivo, "                                </div>"
    Print #Archivo, "                            </div>"
    Print #Archivo, "                        </div>"
    Print #Archivo, "                        <div style='padding: 0 10px;  border-left: 1px solid black; border-right: 1px solid black; background-color: white;'>"
    Print #Archivo, "                            <div>Recibi(mos):</div>"
    Print #Archivo, "                            <div style='display: flex; justify-content: space-between; margin-top: 5px;'>"
    Print #Archivo, "                                <div style='margin-left: 70px; padding: 0 0 10px 0;'>IMPORTE PAGADO</div>"
    Print #Archivo, "                                <div>0,00</div>"
    Print #Archivo, "                            </div>"
    Print #Archivo, "                        </div>"
    Print #Archivo, "                        <div class='footer-section' style='background-color: white; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 1px solid black;'>"
    Print #Archivo, "                            <div style='border-top: 1px dashed #000; padding-top: 10px; background-color: white;'></div>"
    Print #Archivo, "                            <div style='text-align: center;'>Transporte: RETIRA CLIENTE</div>"
    Print #Archivo, "                            <div style='border-top: 1px dashed #000; margin: 5px 248px 0 313px; padding-top: 10px;'></div>"
    Print #Archivo, "                            <div style='border-top: 1px dashed #000; margin: 5px 248px 0 313px; padding-top: 10px;'></div>"
    Print #Archivo, "                                <div style='display: flex; justify-content: space-between;'>"
    Print #Archivo, "                                    <div>((( FLETES A CARGO DEL CLIENTE )))</div> "
    Print #Archivo, "                                    <div style='margin: 0px 76px 0 0;'>00000000</div> "
    Print #Archivo, "                                    <div>(70010045)</div>"
    Print #Archivo, "                                </div>"
    Print #Archivo, "                            <div style='border-top: 1px dashed #000; margin: 10px 0 0 0; padding-top: 10px;'></div>"
    Print #Archivo, "                            <div>"
    Print #Archivo, "                                <div>C.A.I. N° 0765-38126509472</div>"
    Print #Archivo, "                                <div>Fecha de Vencimiento: 11/09/2027</div>"
    Print #Archivo, "                                <div style='display: flex; justify-content: flex-start; gap:3rem'>"
    Print #Archivo, "                                    <div style='margin-left: 10px; font-style: italic;'>CF</div>"
    Print #Archivo, "                                    <div>HHG1614169</div>"
    Print #Archivo, "                                </div>"
    Print #Archivo, "                                <div style='margin-left: 5px; font-style: italic;'>DGI</div>"
    Print #Archivo, "                                <div>147: Telefono Gratuito C.A.B.A., Area de Defensa y Protección al Consumidor</div>"
    Print #Archivo, "                            </div>"
    Print #Archivo, "                        </div>"
    Print #Archivo, "                </div>"
    Print #Archivo, "            </div>"
    Print #Archivo, "        </div>   "
'    Print #Archivo, "        <div style='width: 84.8%; margin-left: 8.4rem; background-color: white; border-left: 1px solid black; border-right: 1px solid black;'> """
'    Print #Archivo, "    </div>     "
'    Print #Archivo, "        <div class='consumer-protection' style='border-left: 1px solid black; border-right: 1px solid black; border-bottom: 1px solid black;'>"
'    Print #Archivo, "            147: Teléfono Gratuito C.A.B.A., Area de Defensa y Protección al Consumidor"
'    Print #Archivo, "        </div>"
    Print #Archivo, "    </div>"
    Print #Archivo, "</body>"
    Print #Archivo, "</html>"
    
    Close #Archivo
    
    ' Abrir el comprobante en el navegador
    Shell "cmd /c start " & ruta, vbNormalFocus
End Function
