Attribute VB_Name = "ModuloUtilidades"
Option Explicit

Global nroFactura As Long

' Convierte un valor de texto en número limpio
Public Function LimpiarValor(ByVal texto As String) As Double
    Dim valorLimpio As String
    valorLimpio = Replace(texto, "$", "")
    valorLimpio = Replace(valorLimpio, ",", "")
    valorLimpio = Trim(valorLimpio)
    
    If IsNumeric(valorLimpio) Then
        LimpiarValor = Val(valorLimpio)
    Else
        LimpiarValor = 0
    End If
End Function

' Formatea un número como precio
Public Function FormatoPrecio(ByVal Valor As Double) As String
    FormatoPrecio = "$" & Format$(Valor, "#,##0.00")
End Function

' Muestra una alerta estándar
Public Sub MostrarAlerta(ByVal mensaje As String)
    MsgBox mensaje, vbExclamation, "Advertencia"
End Sub

Public Function FormatearNumeroFactura(ByVal numero As Long) As String
    FormatearNumeroFactura = Format(numero, "00000000")
End Function

Public Function GenerarComprobante(ByVal subTotal As Double, iva As Integer, total As Double, formulario As Object) As String
    Dim archivo As Integer
    Dim ruta As String
    Dim i As Integer
'    Dim subTotal As Double, iva As Double, total As Double
    ruta = "C:\comprobante.html"
    archivo = FreeFile()
    Open ruta For Output As #archivo
    
    Print #archivo, "<html><head><title>Factura</title></head><body>"
    Print #archivo, "<style>"
    Print #archivo, "body { font-family: Arial, sans-serif; width: 800px; margin: auto; }"
    Print #archivo, ".container { border: 1px solid #000; padding: 0; }"
    Print #archivo, ".header { display: flex; border-bottom: 1px solid #000; position: relative; }"
    Print #archivo, ".logo-section { width: 50%; padding: 10px; }"
    Print #archivo, ".logo { width: 350px; display: block; }"
    Print #archivo, ".company-info { font-size: 12px; margin: 0; }"
    Print #archivo, ".company-space { margin-bottom: 15px; }"
    Print #archivo, ".company-margin { margin: 0 50px;} "
    Print #archivo, ".company-name { font-weight: bold; }"
    Print #archivo, ".email { color: blue; }"
    Print #archivo, ".letter-box {  width: 7%; display: flex; flex-direction: column; height: 100%; /* Añadir posición relativa */ }"
    Print #archivo, ".vertical-blue-line { position: absolute; top: 48%; left: 50%; width: 1px; height: 111px; background-color: black; print-color-adjust: exact; -webkit-print-color-adjust: exact; }"
    Print #archivo, ".letter { font-size: 36px; "
    Print #archivo, "  text-align: center;"
    Print #archivo, "  height: 100%; /* Ocupa todo el alto disponible */"
    Print #archivo, "  display: flex;"
    Print #archivo, "  flex-direction: column;"
    Print #archivo, "  justify-content: center;}"
    Print #archivo, ".letter-border { "
    Print #archivo, "  border-left: 1px solid #000;"
    Print #archivo, "  border-right: 1px solid #000;"
    Print #archivo, "  border-bottom: 1px solid #000;"
    Print #archivo, "  height: 100%; /* Ocupa todo el alto disponible */"
    Print #archivo, "  display: flex;"
    Print #archivo, "  align-items: center; /* Centra el contenido verticalmente */"
    Print #archivo, "  justify-content: center; /* Centra el contenido horizontalmente */"
    Print #archivo, "  min-height: 80px; /* Establece una altura mínima */"
    Print #archivo, "  padding: 10px 0; /* Añade espacio arriba y abajo */} "
    Print #archivo, ".factura-section { width: 50%; padding: 10px; display: flex; flex-direction: column; }"
    Print #archivo, ".factura-label { font-size: 14px; text-align: left; margin-bottom: 10px; }"
    Print #archivo, ".factura-num { font-size: 23px; margin-bottom: 20px; }"
    Print #archivo, ".factura-num-dos {margin-right: 6px;}"
    Print #archivo, ".factura-num-font {font-size: 28px; font-family: 'Courier New', monospace; color: gray}"
    Print #archivo, ".factura-info { text-align: left; margin-top: 35px;}"
    Print #archivo, ".vertical-line { position: absolute; top: 70px; left: 76%; width: 1px; height: calc(100% - 70px); background-color: #000; }"
    Print #archivo, ".items-table { width: 100%; border-collapse: collapse; }"
    Print #archivo, ".items-table th, .items-table td {"
    Print #archivo, "  width: 25%;"
    Print #archivo, "  text-align: center;"
    Print #archivo, "  font-size: 12px;"
    Print #archivo, "}"
    Print #archivo, ".watermark { position: relative; height: 400px; }"
    Print #archivo, ".watermark-content { position: absolute; width: 100%; height: 100%; display: flex; justify-content: center; align-items: center; opacity: 0.1; }"
    Print #archivo, ".watermark-logos { display: flex; justify-content: center; }"
    Print #archivo, ".watermark-logo { margin: 0 20px; }"
    Print #archivo, ".totals-section { "
    Print #archivo, "  display: flex;"
    Print #archivo, "  margin-bottom: 10px;"
    Print #archivo, "}"
    Print #archivo, ".totals-section-border {"
    Print #archivo, "  position: relative;"
    Print #archivo, "  height: 10px; /* Altura del espacio que contiene el borde */"
    Print #archivo, "  margin: 0 auto;"
    Print #archivo, "  width: 94%;"
    Print #archivo, "  border-top: 1px dashed #000;"
    Print #archivo, "}"
    Print #archivo, ".totals-section-border::before {"
    Print #archivo, "  content: '';"
    Print #archivo, "  position: absolute;"
    Print #archivo, "  top: 0;"
    Print #archivo, "  left: 10%; /* Ajusta este valor para controlar dónde comienza el borde */"
    Print #archivo, "  width: 95%; /* Ajusta este valor para controlar el ancho del borde */"
    Print #archivo, "  height: 1px;"
    Print #archivo, "  background-color: transparent; /* Elimina el fondo sólido */"
    Print #archivo, "}"
    Print #archivo, ".subtotal-section { "
    Print #archivo, "  width: 40%; "
    Print #archivo, "  padding: 10px; "
    Print #archivo, "  font-size: 12px; "
    Print #archivo, "}"
    Print #archivo, ".total-section { "
    Print #archivo, "  width: 60%; "
    Print #archivo, "  padding: 10px; "
    Print #archivo, "  text-align: right; "
    Print #archivo, "  font-size: 14px; "
    Print #archivo, "}"
    Print #archivo, ".footer {padding: 0 10px; font-size: 10px; text-align: left; margin: 15px 0;}"
    Print #archivo, ".footer p { margin: 0; }"
    Print #archivo, "@media print {"
    Print #archivo, "  .no-print, .no-print * {"
    Print #archivo, "    display: none !important;"
    Print #archivo, "    visibility: hidden !important;"
    Print #archivo, "  }"
    Print #archivo, "  .vertical-blue-line {"
    Print #archivo, "    position: absolute;"
    Print #archivo, "    top: 49.5%;"
    Print #archivo, "    left: 50%;"
    Print #archivo, "    width: 1px;"
    Print #archivo, "    height: 103px;"
    Print #archivo, "    background-color: black;"
    Print #archivo, "    print-color-adjust: exact;"
    Print #archivo, "    -webkit-print-color-adjust: exact;"
    Print #archivo, "}"
    Print #archivo, "  @page {"
    Print #archivo, "    margin: 0.5cm;"
    Print #archivo, "    size: auto;"
    Print #archivo, "  }"
    Print #archivo, "  html {"
    Print #archivo, "    -webkit-print-color-adjust: exact !important;"
    Print #archivo, "    print-color-adjust: exact !important;"
    Print #archivo, "  }"
    Print #archivo, "  body > *:not(.container) {"
    Print #archivo, "    display: none !important;"
    Print #archivo, "  }"
    Print #archivo, "  .header-date, .print-timestamp, .browser-info {"
    Print #archivo, "    display: none !important;"
    Print #archivo, "  }"
    Print #archivo, "}"
    Print #archivo, "</style>"

    Print #archivo, "<div class='container'>"
    Print #archivo, "<div class='header'>"
    Print #archivo, "  <div class='logo-section'>"
    Print #archivo, "    <button onclick='window.print()' class='no-print'>Imprimir</button>"
    Print #archivo, "    <img src='C:\Users\mlopez\Desktop\mlopez\CLIENTE 2/LOGO1.jpg' class='logo'>"
    Print #archivo, "    <div class='company-margin'>"
    Print #archivo, "      <p class='company-info company-name'>NEUMATICOS ARTURO S.R.L.</p>"
    Print #archivo, "      <p class='company-info'>AV. SAN MARTIN 1695 - 1678 CASEROS</p>"
    Print #archivo, "      <p class='company-info'>TEL.: (011) 4734 - 8476</p>"
    Print #archivo, "      <p class='company-info email'>ventas@neumaticosarturo.com.ar</p>"
    Print #archivo, "      <p class='company-info'>I.V.A.: Responsable Inscripto</p>"
    Print #archivo, "    </div>"
    Print #archivo, "  </div>"
    Print #archivo, "  <div class='letter-box'>"
    Print #archivo, "    <div class='flex letter'>"
    Print #archivo, "      <div class='letter-border'>"
    Print #archivo, "          A"
    Print #archivo, "      </div>"
    Print #archivo, "      <div class='vertical-blue-line'></div>"
    Print #archivo, "    </div>"
    Print #archivo, "  </div>"
    Print #archivo, "  <div class='factura-section'>"
    Print #archivo, "    <div class='factura-label'>FACTURA</div>"
    Print #archivo, "    <div class='factura-num'><span class='factura-num-dos'>N°0001- " & "</span> <span class='factura-num-Font'>" & Format(nroFactura, "00000000") & "</span></div>"
    Print #archivo, "    <div class='factura-info'>"
    Print #archivo, "      <p class='company-info company-space'>FECHA: 17/03/2025</p>"
    Print #archivo, "      <p class='company-info'>C.U.I.T.: 33-71457404-9</p>"
    Print #archivo, "      <p class='company-info'>ING. BRUTOS: 33-71457404-9</p>"
    Print #archivo, "      <p class='company-info'>INICIO DE ACTIVIDADES: 08/2014</p>"
    Print #archivo, "    </div>"
    Print #archivo, "  </div>"
    Print #archivo, "</div>"
    Print #archivo, "<div style='border-bottom: 1px solid #000; height: 60px'></div>"
    Print #archivo, "<table class='items-table'>"
    Print #archivo, "  <tr>"
    Print #archivo, "    <th style='padding: 5px; border-bottom: none; width: 25%; text-align: center; color: gray'>CANTIDAD</th>"
    Print #archivo, "    <th style='padding: 5px; border-bottom: none; width: 32%; text-align: center; color: gray'>DESCRIPCION</th>"
    Print #archivo, "    <th style='padding: 5px; border-bottom: none; width: 25%; text-align: center; color: gray'>P.UNITARIO</th>"
    Print #archivo, "    <th style='padding: 5px; border-bottom: none; width: 25%; text-align: center; color: gray'>TOTAL</th>"
    Print #archivo, "  </tr>"
    Print #archivo, "<tr><td colspan='4'>"
    Print #archivo, "<div class='watermark'>"
    Print #archivo, "  <div class='watermark-content'>"
    Print #archivo, "    <div class='watermark-logos'>"
    Print #archivo, "      <img src='C:\Users\mlopez\Desktop\mlopez\CLIENTE 2\LOGO3.jpg' class='watermark-logo' style='width: 300px'>"
    Print #archivo, "      <img src='C:\Users\mlopez\Desktop\mlopez\CLIENTE 2\LOGO2.jpg' class='watermark-logo' style='width: 300px'>"
    Print #archivo, "    </div>"
    Print #archivo, "  </div>"
    Print #archivo, "  <table style='width: 100%; border: none'>"

    ' Recorrer ListView y agregar filas a la tabla
    With formulario
    For i = 1 To .Grilla.ListItems.Count
        Dim Cantidad As Integer
        Dim Descripcion As String
        Dim PrecioUnitario As Double
        Dim totalProducto As Double

        Cantidad = .Grilla.ListItems(i).SubItems(2)
        Descripcion = .Grilla.ListItems(i).SubItems(1)
        PrecioUnitario = .Grilla.ListItems(i).SubItems(3)
        totalProducto = .Grilla.ListItems(i).SubItems(4)

        Print #archivo, "<tr><td style='width: 25%; text-align: center'>" & Cantidad & "</td>"
        Print #archivo, "<td style='width: 32%; text-align: left; text-transform: uppercase'>" & Descripcion & "</td>"
        Print #archivo, "<td style='width: 25%; text-align: center'>" & Format(PrecioUnitario, "#,##0.00") & "</td>"
        Print #archivo, "<td style='width: 25%; text-align: center'>" & Format(totalProducto, "#,##0.00") & "</td></tr>"

'        subTotal = subTotal + totalProducto
    Next i
    End With
    Print #archivo, "  </table>"
    Print #archivo, "</div>"
    Print #archivo, "</td></tr>"
    Print #archivo, "</table>"
    Print #archivo, "<div style='display: flex'>"
    Print #archivo, "  <div class='subtotal-section'>"
    Print #archivo, "    <div style='display: flex'> "
    Print #archivo, "    <div style='margin-right: 80px'>SUBTOTAL</div>"
    Print #archivo, "    <div>IVA</div>"
    Print #archivo, "  </div>"
    Print #archivo, "<div style='display: flex; margin-top: 5px;'>"
    Print #archivo, "<div style='margin-right: 80px;'>" & Format$(subTotal, "#,##0.00") & "</div>"
    Print #archivo, "<div>(21.00)</div>"
    Print #archivo, "</div>"
    Print #archivo, "  </div>"
    Print #archivo, "  <div class='total-section'>"
    Print #archivo, "    <div>CONCEPTOS NO GRAVADOS</div>"
    Print #archivo, "    <br><br>"
    Print #archivo, "    <div style='display: flex; justify-content: space-between; font-size: 16px; font-weight: bold; text-align: left; padding-left: 50%;'>TOTAL $ <span>" & Format$(total, "#,##0.00") & "</span></div>"
    Print #archivo, "  </div>"
    Print #archivo, "</div>"
    Print #archivo, "<div class='totals-section-border'></div>"
    Print #archivo, "<div class='footer'>"
    Print #archivo, "  <p>C.A.I. N 2175-19625194739</p>"
    Print #archivo, "  <p>Fecha de Vencimiento: 17/04/2025</p>"
    Print #archivo, "  <p style='margin-left: 20px;'>REGISTRO PHG3523973</p>"
    Print #archivo, "</div>"
    Print #archivo, "</div>"
    Print #archivo, "</body></html>"

    Close #archivo
    
    ' Abrir el comprobante en el navegador
    Shell "cmd /c start " & ruta, vbNormalFocus
End Function

Public Function GenerarComprobante2(ByVal subTotal As Double, iva As Integer, total As Double, formulario As Object) As String
    Dim archivo As Integer
    Dim ruta As String
    Dim i As Integer
'    Dim subTotal As Double, iva As Double, total As Double
    ruta = "C:\comprobante2.html"
    archivo = FreeFile()
    Open ruta For Output As #archivo
    
    Print #archivo, "<html>"
    Print #archivo, "<head>"
    Print #archivo, "    <title>Factura Federal Parts</title>"
    Print #archivo, "    <style>"
    Print #archivo, "        body {"
    Print #archivo, "            font-family: Arial, sans-serif;"
    Print #archivo, "            width: 800px;"
    Print #archivo, "            margin: auto;"
    Print #archivo, "            background-color: #a9dff9;"
    Print #archivo, "        }"
    Print #archivo, "        .container {"
    Print #archivo, "            padding: 0;"
    Print #archivo, "            background-color: #a9dff9;"
    Print #archivo, "        }"
    Print #archivo, "        .header {"
    Print #archivo, "            display: flex;"
    Print #archivo, "            justify-content: space-between;"
    Print #archivo, "            padding: 10px 20px;"
    Print #archivo, "        }"
    Print #archivo, "        .logo-section { display: flex; width: 45%; }"
    Print #archivo, "        .logo-fp {"
    Print #archivo, "            display: flex;"
    Print #archivo, "            flex-direction: column;"
    Print #archivo, "            margin-left: 10px;"
    Print #archivo, "        }"
    Print #archivo, "        .fp-text {"
    Print #archivo, "            color: #FF0000;"
    Print #archivo, "            letter-spacing: 7px;"
    Print #archivo, "            font-family: Arial, Helvetica, sans-serif;"
    Print #archivo, "            font-size: 23px;"
    Print #archivo, "            font-weight: 800;"
    Print #archivo, "            margin: 0;"
    Print #archivo, "        }"
    Print #archivo, "        .repuestos-text {"
    Print #archivo, "            letter-spacing: 2px;"
    Print #archivo, "            font-size: 17px;"
    Print #archivo, "            font-weight: bold;"
    Print #archivo, "            margin: 0;"
    Print #archivo, "        }"
    Print #archivo, "        .phone-numbers {"
    Print #archivo, "            font-size: 14px;"
    Print #archivo, "            margin-top: 10px;"
    Print #archivo, "            font-weight: bold;"
    Print #archivo, "        }"
    Print #archivo, "        .blue-square {"
    Print #archivo, "            width: 80px;"
    Print #archivo, "            height: 80px;"
    Print #archivo, "            background-color: #000080;"
    Print #archivo, "            margin-right: 10px;"
    Print #archivo, "            display: flex;"
    Print #archivo, "            justify-content: center;"
    Print #archivo, "            align-items: center;"
    Print #archivo, "        }"
    Print #archivo, "        .fp-logo {"
    Print #archivo, "            color: #FF0000;"
    Print #archivo, "            font-size: 36px;"
    Print #archivo, "            font-weight: bold;"
    Print #archivo, "        }"
    Print #archivo, "        .company-box {"
    Print #archivo, "            border: 1px solid #000;"
    Print #archivo, "            padding: 18px;"
    Print #archivo, "            margin-top: 10px;"
    Print #archivo, "            background-color: white;"
    Print #archivo, "            width: 85%;"
    Print #archivo, "        }"
    Print #archivo, "        .invoice-box {"
    Print #archivo, "            display: flex;"
    Print #archivo, "            gap:1rem;"
    Print #archivo, "            align-items: center;"
    Print #archivo, "            border: 1px solid #000;"
    Print #archivo, "            padding: 8.5px;"
    Print #archivo, "            background-color: white;"
    Print #archivo, "            margin-top: 10px;"
    Print #archivo, "        }"
    Print #archivo, "        .tfact-box {"
    Print #archivo, "            border: 1px solid #000;"
    Print #archivo, "            padding: 9px 10px;"
    Print #archivo, "            background-color: white;"
    Print #archivo, "            width: 85%;"
    Print #archivo, "        }"
    Print #archivo, "        .tfact-box p {"
    Print #archivo, "            text-align: center;"
    Print #archivo, "            font-size: 30px;"
    Print #archivo, "            margin-block-start: 10px;"
    Print #archivo, "            margin-block-end: 10px;"
    Print #archivo, "        }"
    Print #archivo, "        .original-copy {"
    Print #archivo, "            text-align: center;"
    Print #archivo, "            font-size: 12px;"
    Print #archivo, "            margin-bottom: 10px;"
    Print #archivo, "            padding: 25px 0;"
    Print #archivo, "        }"
    Print #archivo, "        .factura-text {"
    Print #archivo, "            font-size: 18px;"
    Print #archivo, "            margin-bottom: 5px;"
    Print #archivo, "        }"
    Print #archivo, "        .factura-num {"
    Print #archivo, "            font-family: 'Courier New', monospace;"
    Print #archivo, "            font-size: 16px;"
    Print #archivo, "        }"
    Print #archivo, "        .date-section {"
    Print #archivo, "            margin-top: 10px;"
    Print #archivo, "            font-size: 12px;"
    Print #archivo, "        }"
    Print #archivo, "        .side-logos {"
    Print #archivo, "            display: flex;"
    Print #archivo, "            flex-direction: column;"
    Print #archivo, "            margin-right: 4rem;"
    Print #archivo, "        }"
    Print #archivo, "        .side-logo {"
    Print #archivo, "            width: 100px;"
    Print #archivo, "            height: 70px;"
    Print #archivo, "            margin-bottom: 20px;"
    Print #archivo, "            text-align: center;"
    Print #archivo, "            display: flex;"
    Print #archivo, "            justify-content: center;"
    Print #archivo, "            align-items: center;"
    Print #archivo, "        }"
    Print #archivo, "        .bosch-logo {"
    Print #archivo, "            background-color: #FF0000;"
    Print #archivo, "            color: white;"
    Print #archivo, "            font-size: 24px;"
    Print #archivo, "            font-weight: bold;"
    Print #archivo, "        }"
    Print #archivo, "        .stanadyne-logo {"
    Print #archivo, "            background-color: #000080;"
    Print #archivo, "            color: white;"
    Print #archivo, "            font-size: 16px;"
    Print #archivo, "            font-weight: bold;"
    Print #archivo, "        }"
    Print #archivo, "        .delphi-logo {"
    Print #archivo, "            background-color: #FF0000;"
    Print #archivo, "            color: white;"
    Print #archivo, "            font-size: 20px;"
    Print #archivo, "            font-weight: bold;"
    Print #archivo, "            border-radius: 50%;"
    Print #archivo, "            width: 100px;"
    Print #archivo, "            height: 100px;"
    Print #archivo, "        }"
    Print #archivo, "        .denso-logo {"
    Print #archivo, "            background-color: #FF0000;"
    Print #archivo, "            color: white;"
    Print #archivo, "            font-size: 20px;"
    Print #archivo, "            font-weight: bold;"
    Print #archivo, "        }"
    Print #archivo, "        .client-section {"
    Print #archivo, "            border: 1px solid #000;"
    Print #archivo, "            padding: 10px;"
    Print #archivo, "            background-color: white;"
    Print #archivo, "            display: flex;"
    Print #archivo, "            min-height: 48px;"
    Print #archivo, "            margin-bottom: 10px;"
    Print #archivo, "        }"
    Print #archivo, "        .items-table {"
    Print #archivo, "            width: 100%;"
    Print #archivo, "            background-color: white;"
    Print #archivo, "            border-top: 1px solid black;"
    Print #archivo, "            border-left: 1px solid black;"
    Print #archivo, "            border-right: 1px solid black;"
    Print #archivo, "        }"
    Print #archivo, "        .items-table th {"
    Print #archivo, "            padding: 5px;"
    Print #archivo, "            text-align: center;"
    Print #archivo, "            background-color: white;"
    Print #archivo, "        }"
    Print #archivo, "        .items-table td {"
    Print #archivo, "            text-align: center;"
    Print #archivo, "        }"
    Print #archivo, "        .totals-section {"
    Print #archivo, "            display: flex;"
    Print #archivo, "            justify-content: space-between;"
    Print #archivo, "            margin: 10px 20px;"
    Print #archivo, "            font-size: 12px;"
    Print #archivo, "        }"
    Print #archivo, "        .subtotal-section {"
    Print #archivo, "            display: flex;"
    Print #archivo, "            gap: 30px;"
    Print #archivo, "        }"
    Print #archivo, "        .total-amount {"
    Print #archivo, "            font-weight: bold;"
    Print #archivo, "            font-size: 16px;"
    Print #archivo, "        }"
    Print #archivo, "        .footer-section {"
    Print #archivo, "            padding: 0 10px 10px 10px;"
    Print #archivo, "            font-size: 12px;"
    Print #archivo, "        }"
    Print #archivo, "        .footer-line {"
    Print #archivo, "            display: flex;"
    Print #archivo, "            justify-content: space-between;"
    Print #archivo, "            margin-bottom: 10px;"
    Print #archivo, "        }"
    Print #archivo, "        .consumer-protection {"
    Print #archivo, "            font-size: 14px;"
    Print #archivo, "            padding: 10px 0 10px 10px;"
    Print #archivo, "            font-weight: bold;"
    Print #archivo, "            width: 83.5%;"
    Print #archivo, "            margin-left: 8.4rem;"
    Print #archivo, "            background-color: white;"
    Print #archivo, "        }"
    Print #archivo, "        .watermark { position: relative; height: 400px; }"
    Print #archivo, "        .subtotal-section { "
    Print #archivo, "            display: block;"
    Print #archivo, "            width: 40%; "
    Print #archivo, "            padding: 10px; "
    Print #archivo, "            font-size: 12px; "
    Print #archivo, "        }"
    Print #archivo, "        .total-section { "
    Print #archivo, "            width: 60%; "
    Print #archivo, "            padding: 10px; "
    Print #archivo, "            text-align: right; "
    Print #archivo, "            font-size: 14px; "
    Print #archivo, "        }"
    Print #archivo, "        @media print {"
    Print #archivo, "            .no-print, .no-print * {"
    Print #archivo, "                display: none !important;"
    Print #archivo, "                visibility: hidden !important;"
    Print #archivo, "            }"
    Print #archivo, "            .vertical-blue-line {"
    Print #archivo, "                position: absolute;"
    Print #archivo, "                top: 49.5%;"
    Print #archivo, "                left: 50%;"
    Print #archivo, "                width: 1px;"
    Print #archivo, "                height: 103px;"
    Print #archivo, "                background-color: black;"
    Print #archivo, "                print-color-adjust: exact;"
    Print #archivo, "                -webkit-print-color-adjust: exact;"
    Print #archivo, "            }"
    Print #archivo, "            @page {"
    Print #archivo, "                margin: 0.5cm;"
    Print #archivo, "                size: auto;"
    Print #archivo, "                background-color: #a9dff9 !important;"
    Print #archivo, "            }"
    Print #archivo, "            html {"
    Print #archivo, "                -webkit-print-color-adjust: exact !important;"
    Print #archivo, "                print-color-adjust: exact !important;"
    Print #archivo, "            }"
    Print #archivo, "            body > *:not(.container) {"
    Print #archivo, "                display: none !important;"
    Print #archivo, "            }"
    Print #archivo, "            .header-date, .print-timestamp, .browser-info {"
    Print #archivo, "                display: none !important;"
    Print #archivo, "            }"
    Print #archivo, "        }"
    Print #archivo, "    </style>"
    Print #archivo, "</head>"
    Print #archivo, "<body>"
    Print #archivo, "    <div class='Container'>"
    Print #archivo, "        <div class='header'>"
    Print #archivo, "            <div class='logo-section'>"
    Print #archivo, "                <img src='C:\Users\mlopez\Desktop\mlopez\CLIENTE 2\LOGO4.jpg' style='width: 70px; height: 100px; display: block'>"
    Print #archivo, "                <div class='logo-fp'>"
    Print #archivo, "                    <div>"
    Print #archivo, "                        <p class='fp-Text'>Federal Parts</p>"
    Print #archivo, "                        <p class='repuestos-Text'>REPUESTOS AUTOMOTOR</p>"
    Print #archivo, "                    </div>"
    Print #archivo, "                    <div class='phone-numbers'>"
    Print #archivo, "                        <p style='margin: 0'>011-5713-7182</p>"
    Print #archivo, "                        <p style='margin: 0'>011-4541-1361</p>"
    Print #archivo, "                        <p style='margin: 0'>011-4541-2845</p>"
    Print #archivo, "                    </div>"
    Print #archivo, "                    <div class='company-box'>"
    Print #archivo, "                        <p style='margin: 2px 0;'>FEDERAL PARTS S.R.L.</p>"
    Print #archivo, "                        <p style='margin: 2px 0;'>JARAMILLO 3060 (1430)</p>"
    Print #archivo, "                        <p style='margin: 2px 0;'>CIUDAD AUTONOMA DE BS. AS.</p>"
    Print #archivo, "                        <p style='margin: 2px 0;'>IVA RESPONSABLE INSCRIPTO</p>"
    Print #archivo, "                    </div>"
    Print #archivo, "                </div>"
    Print #archivo, "            </div>"
    Print #archivo, "            <div>"
    Print #archivo, "                <div class='tfact-box'>"
    Print #archivo, "                    <p>A</p>"
    Print #archivo, "                </div>"
    Print #archivo, "            </div>"
    Print #archivo, "            <div style='width: 25rem;'>"
    Print #archivo, "                <div class='original-Copy'>ORIGINAL BLANCO / COPIA COLOR</div>"
    Print #archivo, "                <div class='invoice-box'>"
    Print #archivo, "                    <div class='factura-Text'>Factura</div>"
    Print #archivo, "                    <div class='factura-num'>N°0001- <span>" & Format(nroFactura, "00000000") & "</span></div>"
    Print #archivo, "                </div>"
    Print #archivo, "                <div class='invoice-box'>"
    Print #archivo, "                    <div class='Date-Section'>"
    Print #archivo, "                        <p style='margin: 2px 0;'>Fecha: 11/09/2020</p>"
    Print #archivo, "                        <p style='margin: 2px 0;'>C.U.I.T.: 30715978735</p>"
    Print #archivo, "                        <p style='margin: 2px 0;'>Ingresos Brutos: 1547261-2</p>"
    Print #archivo, "                        <p style='margin: 2px 0;'>Inicio de Actividades: 01/03/2018</p>"
    Print #archivo, "                    </div>"
    Print #archivo, "                </div>"
    Print #archivo, "            </div>"
    Print #archivo, "        </div>"
    Print #archivo, "        <div style='display: flex;'>"
    Print #archivo, "            <div class='side-logos'>"
    Print #archivo, "                <img src='C:\Users\mlopez\Desktop\mlopez\CLIENTE 2\LOGO5.jpg' style=' width: 53px; height: 120px; display: block;'>"
    Print #archivo, "                <img src='C:\Users\mlopez\Desktop\mlopez\CLIENTE 2\LOGO6.jpg' style=' width: 53px; height: 120px; display: block; margin-top: 10px;'>"
    Print #archivo, "                <img src='C:\Users\mlopez\Desktop\mlopez\CLIENTE 2\LOGO7.jpg' style=' width: 53px; height: 120px; display: block; margin-top: 10px;'>"
    Print #archivo, "                <img src='C:\Users\mlopez\Desktop\mlopez\CLIENTE 2\LOGO8.jpg' style=' width: 53px; height: 120px; display: block; margin-top: 10px;'>"
    Print #archivo, "            </div>"
    Print #archivo, "            <div style='width: 85%;'>"
    Print #archivo, "                <div class='client-Section'>"
    Print #archivo, "                </div>"
    Print #archivo, "                <div class='watermark'>"
    Print #archivo, "                        <table class='items-Table' style='height: 80%;'>"
    Print #archivo, "                            <tr>"
    Print #archivo, "                                <th>CANTIDAD</th>"
    Print #archivo, "                                <th>DESCRIPCION</th>"
    Print #archivo, "                                <th>PRECIO UNITARIO</th>"
    Print #archivo, "                                <th>PRECIO NETO</th>"
    Print #archivo, "                            </tr>"
' Recorrer ListView y agregar filas a la tabla
    With formulario
    For i = 1 To .Grilla.ListItems.Count
        Dim Cantidad As Integer
        Dim Descripcion As String
        Dim PrecioUnitario As Double
        Dim totalProducto As Double

        Cantidad = .Grilla.ListItems(i).SubItems(2)
        Descripcion = .Grilla.ListItems(i).SubItems(1)
        PrecioUnitario = .Grilla.ListItems(i).SubItems(3)
        totalProducto = .Grilla.ListItems(i).SubItems(4)

        Print #archivo, "<tr><td style='width: 15%; text-align: center'>" & Cantidad & "</td>"
        Print #archivo, "<td style='width: 40%; text-align: left; text-transform: uppercase'>" & Descripcion & "</td>"
        Print #archivo, "<td style='width: 25%; text-align: center'>" & Format(PrecioUnitario, "#,##0.00") & "</td>"
        Print #archivo, "<td style='width: 25%; text-align: center'>" & Format(totalProducto, "#,##0.00") & "</td></tr>"

'        subTotal = subTotal + totalProducto
    Next i
    End With
    Print #archivo, "                        </table>"
    Print #archivo, "                        <div style='padding-top: 10px; text-align: center; background-color: white; border-left: 1px solid black; border-right: 1px solid black;'>"
    Print #archivo, "                            <p class='fp-Text'>Federal Parts</p>"
    Print #archivo, "                            <p class='repuestos-Text'>REPUESTOS AUTOMOTOR</p>"
    Print #archivo, "                        </div>"
    Print #archivo, "                        <div style='display: flex; padding-top: 15px; background-color: white; border-left: 1px solid black; border-right: 1px solid black;'>"
    Print #archivo, "                            <div class='subtotal-section'>"
    Print #archivo, "                                <div style='display: flex; align-items: center; gap: 3rem;'>"
    Print #archivo, "                                    <div>SUBTOTAL</div>"
    Print #archivo, "                                    <div style='width: 100px; flex-shrink: 0;'>ALICUOTA IVA</div>"
    Print #archivo, "                                    <div style='width: 90px; flex-shrink: 0;'>IVA RECEP. IVA</div>"
    Print #archivo, "                                    <div style='width: 90px; flex-shrink: 0;'>RECEP. OTROS</div>"
    Print #archivo, "                                    <div style='width: 180px; flex-shrink: 0;'>CONCEPTOS NO GRAVADOS</div>"
    Print #archivo, "                                </div>"
    Print #archivo, "                                <div style='display: flex; margin-top: 5px;'>"
    Print #archivo, "                                    <div style='margin-right: 54px;'>" & Format$(subTotal, "#,##0.00") & "</div>"
    Print #archivo, "                                    <div style='margin-right: 98px;'>(21.00)</div>"
    Print #archivo, "                                    <div style='margin-right: 320px;'>" & Format$(iva, "#,##0.00") & "</div>"
    Print #archivo, "                                    <div>00.00</div>"
    Print #archivo, "                                </div>"
    Print #archivo, "                            </div>"
    Print #archivo, "                        </div>"
    Print #archivo, "                        <div style='padding: 10px; text-align: -webkit-right; background-color: white; border-left: 1px solid black; border-right: 1px solid black;'>"
    Print #archivo, "                            <div style='width: 50%; text-align: right;'>"
    Print #archivo, "                                <div style='margin-top: 10px; font-weight: bold; font-size: 18px; text-align: right;'>"
    Print #archivo, "                                    <span style='margin-right: 10rem;'>TOTAL $</span>" & Format$(total, "#,##0.00")
    Print #archivo, "                                </div>"
    Print #archivo, "                            </div>"
    Print #archivo, "                        </div>"
    Print #archivo, "                        <div style='padding: 0 10px;  border-left: 1px solid black; border-right: 1px solid black; background-color: white;'>"
    Print #archivo, "                            <div>Recibi(mos):</div>"
    Print #archivo, "                            <div style='display: flex; justify-content: space-between; margin-top: 5px;'>"
    Print #archivo, "                                <div style='margin-left: 70px; padding: 0 0 10px 0;'>IMPORTE PAGADO</div>"
    Print #archivo, "                                <div>0,00</div>"
    Print #archivo, "                            </div>"
    Print #archivo, "                        </div>"
    Print #archivo, "                        <div class='footer-section' style='background-color: white; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 1px solid black;'>"
    Print #archivo, "                            <div style='border-top: 1px dashed #000; padding-top: 10px; background-color: white;'></div>"
    Print #archivo, "                            <div style='text-align: center;'>Transporte: RETIRA CLIENTE</div>"
    Print #archivo, "                            <div style='border-top: 1px dashed #000; margin: 5px 248px 0 313px; padding-top: 10px;'></div>"
    Print #archivo, "                            <div style='border-top: 1px dashed #000; margin: 5px 248px 0 313px; padding-top: 10px;'></div>"
    Print #archivo, "                                <div style='display: flex; justify-content: space-between;'>"
    Print #archivo, "                                    <div>((( FLETES A CARGO DEL CLIENTE )))</div> "
    Print #archivo, "                                    <div style='margin: 0px 76px 0 0;'>00000000</div> "
    Print #archivo, "                                    <div>(70010045)</div>"
    Print #archivo, "                                </div>"
    Print #archivo, "                            <div style='border-top: 1px dashed #000; margin: 10px 0 0 0; padding-top: 10px;'></div>"
    Print #archivo, "                            <div>"
    Print #archivo, "                                <div>C.A.I. N° 0765-38126509472</div>"
    Print #archivo, "                                <div>Fecha de Vencimiento: 11/09/2020</div>"
    Print #archivo, "                                <div style='display: flex; justify-content: flex-start; gap:3rem'>"
    Print #archivo, "                                    <div style='margin-left: 10px; font-style: italic;'>CF</div>"
    Print #archivo, "                                    <div>HHG1614169</div>"
    Print #archivo, "                                </div>"
    Print #archivo, "                                <div style='margin-left: 5px; font-style: italic;'>DGI</div>"
    Print #archivo, "                            </div>"
    Print #archivo, "                        </div>"
    Print #archivo, "                </div>"
    Print #archivo, "            </div>"
    Print #archivo, "        </div>   "
    Print #archivo, "        <div style='width: 84.8%; margin-left: 8.4rem; background-color: white; border-left: 1px solid black; border-right: 1px solid black;'> """
    Print #archivo, "    </div>     "
    Print #archivo, "        <div class='consumer-protection' style='border-left: 1px solid black; border-right: 1px solid black; border-bottom: 1px solid black;'>"
    Print #archivo, "            147: Teléfono Gratuito C.A.B.A., Area de Defensa y Protección al Consumidor"
    Print #archivo, "        </div>"
    Print #archivo, "    </div>"
    Print #archivo, "</body>"
    Print #archivo, "</html>"
    
    Close #archivo
    
    ' Abrir el comprobante en el navegador
    Shell "cmd /c start " & ruta, vbNormalFocus
End Function
