CREATE TABLE FACTURAS
(
	FACTURA INT IDENTITY(1,1) PRIMARY KEY,
	TIPO    CHAR(1)
)

CREATE TABLE PRODUCTOS_VENTAS
(
	ID              INT IDENTITY(1,1) PRIMARY KEY,
	DESCRIPCION     VARCHAR(255) NOT NULL,
	CANTIDAD        INT NOT NULL,
	PRECIO_UNITARIO NUMERIC(18,2) NOT NULL,
	PRECIO_NETO     NUMERIC(18,2) NOT NULL,
	SUBTOTAL        NUMERIC(18,2) NOT NULL,
	IVA             DECIMAL(2,2) DEFAULT(21.00),
	TOTAL           NUMERIC(18,2) NOT NULL,
	FACTURA         INT NOT NULL,
                    CONSTRAINT FK_Producto_Producto FOREIGN KEY (FACTURA) 
                    REFERENCES FACTURAS(FACTURA) 
                    ON DELETE CASCADE  -- Si se borra una factura, sus productos también se eliminan
)

