CREATE TABLE FACTURAS
(
	FACTURA INT IDENTITY(1,1) PRIMARY KEY,
	TIPO    CHAR(1)
)
select * from PRODUCTOS_VENTAS
CREATE TABLE PRODUCTOS_VENTAS
(
	ID              INT IDENTITY(1,1) PRIMARY KEY,
	DESCRIPCION     VARCHAR(255) NOT NULL,
	CANTIDAD        INT NOT NULL,
	PRECIO_UNITARIO NUMERIC(18,2) NOT NULL,
	PRECIO_NETO     NUMERIC(18,2) NOT NULL,
	FACTURA         INT NOT NULL,
                    CONSTRAINT FK_Producto_Producto FOREIGN KEY (FACTURA) 
                    REFERENCES FACTURAS(FACTURA) 
                    ON DELETE CASCADE  -- Si se borra una factura, sus productos también se eliminan
)


INSERT INTO FACTURAS SELECT 'A'
INSERT INTO PRODUCTOS_VENTAS SELECT 'A',1,1,1,2


TRUNCATE TABLE FACTURAS